### ISSUE TITLE
No luck

### ISSUE THREAD

**Issue by Gunni** [morrowc/rislive#1]
1. trying to run it

```
[notandi@gil rislive]$ go run .
Reading from the firehose...
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: {ris_message 0xc0005b80c0}
^Csignal: interrupt
```

2. Trying to test it

```
[notandi@gil rislive]$ go test
# _/home/notandi/rislive
rislive_test.go:6:2: cannot find package "github.com/golang/protobuf/proto" in any of:
        /usr/lib/golang/src/github.com/golang/protobuf/proto (from $GOROOT)
        /home/notandi/go/src/github.com/golang/protobuf/proto (from $GOPATH)
FAIL    _/home/notandi/rislive [setup failed]
[notandi@gil rislive]$ go test .
# _/home/notandi/rislive
rislive_test.go:6:2: cannot find package "github.com/golang/protobuf/proto" in any of:
        /usr/lib/golang/src/github.com/golang/protobuf/proto (from $GOROOT)
        /home/notandi/go/src/github.com/golang/protobuf/proto (from $GOPATH)
FAIL    _/home/notandi/rislive [setup failed]
[notandi@gil rislive]$ go get github.com/golang/protobuf/proto
[notandi@gil rislive]$ go test
# _/home/notandi/rislive
rislive_test.go:7:2: cannot find package "github.com/google/go-cmp/cmp" in any of:
        /usr/lib/golang/src/github.com/google/go-cmp/cmp (from $GOROOT)
        /home/notandi/go/src/github.com/google/go-cmp/cmp (from $GOPATH)
FAIL    _/home/notandi/rislive [setup failed]
[notandi@gil rislive]$ go get github.com/google/go-cmp/cmp
[notandi@gil rislive]$ go test
failed to convert filter prefix(192.b.0.0/16) to IPNet: invalid CIDR address: 192.b.0.0/16announcement prefix(192.b.0.0/24) not parsed as CIDR: invalid CIDR address: 192.b.0.0/24PASS
ok      _/home/notandi/rislive  0.003s
```

Got some work to do or is it broken?

**Comment by morrowc** [comment]
Testing a fresh install:
$ git clone https://github.com/morrowc/rislive.git
$ cd rislive
$ go run .
Reading from the firehose...
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
...

This looks like something changed in the inbound JSON stream :( great!
I'll have to go looking for this today, thanks!

for the testing:
$ go test ./...
ok  	_/tmp/rislive	0.036s
$ go test 
failed to convert filter prefix(192.b.0.0/16) to IPNet: invalid CIDR address: 192.b.0.0/16announcement prefix(192.b.0.0/24) not parsed as CIDR: invalid CIDR address: 192.b.0.0/24PASS
ok  	_/tmp/rislive	0.037s

The 'failed to convert' is a rando Printf() I believe... so  oops! I'll remove that.
I'm not sure why I have used protobuf libraries in the tests, so I'll see about unraveling that as well today.
Thanks!

**Comment by morrowc** [comment]
Ok, I know why protobuf/proto is used:
  Making a pointer to a string is 'hard', but proto.String() does it for you for 'free'.

The rand fmt.Printf is fixed now, to a log message...

**Comment by morrowc** [comment]
https://github.com/morrowc/rislive/commit/cb4b36da3d47cfb133edd4b88e0d2f1999d1c030

partial fixes in that change.

**Comment by morrowc** [comment]
It looks, to me, like messages of this form:
failed to decode json: json: cannot unmarshal array into Go struct field RisMessageData.path of type int32
bad json content: &{Timestamp:1.57362308572e+09 Peer:198.58.198.254 PeerASN:1403 ID:00-198-58-198-254-6778817 Host:rrc00 Type:UPDATE Path:[1403 174 2914 12252 23487 27738 52989] Community:[[14032 174]] Origin:igp Announcements:[0xc00008d170] Raw:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF005B02000000404001010040022002060000057B000000AE00000B6200002FDC00005BBF00006C5A010100006C5A400304C63AC6FEC0070800005BBFC87CF701C0080436D000AE18C9B7FF}


are causing the decode error, I don't think this is every message, however.
these messages appear to be conforming to the proper json formatting.

**Comment by morrowc** [comment]
Ah! So, I believe the failing json messages have this (not the above) content:
{"type":"ris_message","data":{"timestamp":1573641026.08,"peer":"80.249.208.111","peer_asn":"30132","id":"03-80-249-208-111-2001948","raw":"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0064020000004940010102400230020A000075B4000019350000370000005BBF00006C5A00006C5A00006C5A00006C5A00006C5A00006C5A010100006C5AC0070800005BBFC87CF70240030450F9D1A718C9B7FF","host":"rrc03","type":"UPDATE","path":[30132,6453,14080,23487,27738,27738,27738,27738,27738,27738,[27738]],"origin":"incomplete","aggregator":"23487:200.124.247.2","announcements":[{"next_hop":"80.249.209.167","prefixes":["201.183.255.0/24"]}]}}


Note the path there is:
"path":[30132,6453,14080,23487,27738,27738,27738,27738,27738,27738,[27738]],

that path as seen from a real bgp speaker:
AS path: 6762 23487 27738 27738 27738 27738 27738 27738 27738 27738 {27738} ?, 

So, I think really there are instances of 'as-set' in the path which rislive is perhaps not encoding very well.

**Comment by morrowc** [comment]
Ok, flakey test problem resolved I believe, as well as parsing of as-set (or not parsing, but not erroring quite as badly).

There are likely still some sharp edges, and I'm waiting on another partner to opensource an LPM library for golang that's reasonable :) but.. progress.

**Comment by morrowc** [comment]
I believe this issue to be resolved, if you get a chance to test again please do.
Note though that the prefix-matching portion (insert seinfeld meme here) is not currently working... so that's one of the 'sharp edges' above, sorry. Still working this part out.
